services:
  - type: web
    name: color-scan
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production

  - type: cron
    name: cleanup-job
    plan: free
    schedule: "@daily"  # 1x/jour
    command: "python cleaner.py"
