stars = [
    {'name': 'Beyoncé', 'follower_count': 200, 'description': 'Musician and global icon', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 500, 'description': 'Football legend', 'country': 'Portugal'},
    {'name': 'Taylor Swift', 'follower_count': 250, 'description': 'Pop superstar', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 300, 'description': 'Actor and former wrestler', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 450, 'description': 'Football icon', 'country': 'Argentina'},
    {'name': 'Rihanna', 'follower_count': 180, 'description': 'Musician and entrepreneur', 'country': 'Barbados'},
    {'name': 'Justin Bieber', 'follower_count': 220, 'description': 'Pop sensation', 'country': 'Canada'},
    {'name': 'Ariana Grande', 'follower_count': 270, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 150, 'description': 'Global music star', 'country': 'Colombia'},
    {'name': 'Tom Cruise', 'follower_count': 120, 'description': 'Hollywood actor', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower_count': 260, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 190, 'description': 'Football superstar', 'country': 'Brazil'},
    {'name': 'Katy Perry', 'follower_count': 160, 'description': 'Pop singer', 'country': 'United States'},
    {'name': 'Leonardo DiCaprio', 'follower_count': 130, 'description': 'Actor and environmentalist', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 170, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Drake', 'follower_count': 140, 'description': 'Rapper and singer', 'country': 'Canada'},
    {'name': 'Adele', 'follower_count': 155, 'description': 'Grammy-winning singer', 'country': 'United Kingdom'},
    {'name': 'Will Smith', 'follower_count': 145, 'description': 'Actor and rapper', 'country': 'United States'},
    {'name': 'Lady Gaga', 'follower_count': 175, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 210, 'description': 'Cricket superstar', 'country': 'India'},
    {'name': 'Brad Pitt', 'follower_count': 110, 'description': 'Hollywood actor', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 135, 'description': 'Alternative pop star', 'country': 'United States'},
    {'name': 'Kylian Mbappé', 'follower_count': 160, 'description': 'Football prodigy', 'country': 'France'},
    {'name': 'Angelina Jolie', 'follower_count': 125, 'description': 'Actress and humanitarian', 'country': 'United States'},
    {'name': 'Ed Sheeran', 'follower_count': 140, 'description': 'Singer-songwriter', 'country': 'United Kingdom'},
    {'name': 'Kim Kardashian', 'follower_count': 280, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Robert Downey Jr.', 'follower_count': 115, 'description': 'Actor and Marvel star', 'country': 'United States'},
    {'name': 'Nicki Minaj', 'follower_count': 150, 'description': 'Rapper and singer', 'country': 'Trinidad and Tobago'},
    {'name': 'Zlatan Ibrahimović', 'follower_count': 130, 'description': 'Football icon', 'country': 'Sweden'},
    {'name': 'Miley Cyrus', 'follower_count': 145, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Chris Hemsworth', 'follower_count': 120, 'description': 'Actor and Thor star', 'country': 'Australia'},
    {'name': 'Priyanka Chopra', 'follower_count': 135, 'description': 'Actress and global star', 'country': 'India'},
    {'name': 'Harry Styles', 'follower_count': 150, 'description': 'Musician and actor', 'country': 'United Kingdom'},
    {'name': 'Scarlett Johansson', 'follower_count': 110, 'description': 'Actress and Marvel star', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 175, 'description': 'Basketball legend', 'country': 'United States'},
    {'name': 'Eminem', 'follower_count': 130, 'description': 'Rap legend', 'country': 'United States'},
    {'name': 'Gal Gadot', 'follower_count': 115, 'description': 'Actress and Wonder Woman star', 'country': 'Israel'},
    {'name': 'Bruno Mars', 'follower_count': 140, 'description': 'Musician and performer', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 160, 'description': 'Football icon and style influencer', 'country': 'United Kingdom'},
    {'name': 'Zendaya', 'follower_count': 145, 'description': 'Actress and fashion icon', 'country': 'United States'},
    {'name': 'Kanye West', 'follower_count': 180, 'description': 'Rapper and fashion mogul', 'country': 'United States'},
    {'name': 'Margot Robbie', 'follower_count': 120, 'description': 'Actress and producer', 'country': 'Australia'},
    {'name': 'Snoop Dogg', 'follower_count': 125, 'description': 'Rapper and cultural icon', 'country': 'United States'},
    {'name': 'Karol G', 'follower_count': 130, 'description': 'Latin music superstar', 'country': 'Colombia'},
    {'name': 'Ryan Reynolds', 'follower_count': 115, 'description': 'Actor and entrepreneur', 'country': 'Canada'},
    {'name': 'Dua Lipa', 'follower_count': 140, 'description': 'Pop sensation', 'country': 'United Kingdom'},
    {'name': 'Usain Bolt', 'follower_count': 150, 'description': 'Sprint legend', 'country': 'Jamaica'},
    {'name': 'Natalie Portman', 'follower_count': 110, 'description': 'Actress and filmmaker', 'country': 'Israel'},
    {'name': 'The Weeknd', 'follower_count': 160, 'description': 'R&B and pop star', 'country': 'Canada'},
    {'name': 'Serena Williams', 'follower_count': 145, 'description': 'Tennis legend', 'country': 'United States'},
    {'name': 'Johnny Depp', 'follower_count': 120, 'description': 'Actor and musician', 'country': 'United States'},
    {'name': 'Camila Cabello', 'follower_count': 130, 'description': 'Pop singer', 'country': 'Cuba'},
    {'name': 'Kevin Hart', 'follower_count': 135, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 125, 'description': 'TV host and comedian', 'country': 'United States'},
    {'name': 'Vin Diesel', 'follower_count': 115, 'description': 'Action movie star', 'country': 'United States'},
    {'name': 'Cardi B', 'follower_count': 150, 'description': 'Rapper and personality', 'country': 'United States'},
    {'name': 'Chris Pratt', 'follower_count': 110, 'description': 'Actor and Jurassic star', 'country': 'United States'},
    {'name': 'Maluma', 'follower_count': 130, 'description': 'Latin music star', 'country': 'Colombia'},
    {'name': 'Emma Watson', 'follower_count': 120, 'description': 'Actress and activist', 'country': 'United Kingdom'},
    {'name': 'Shawn Mendes', 'follower_count': 135, 'description': 'Pop singer', 'country': 'Canada'},
    {'name': 'Gigi Hadid', 'follower_count': 140, 'description': 'Supermodel', 'country': 'United States'},
    {'name': 'Ronaldinho', 'follower_count': 145, 'description': 'Football legend', 'country': 'Brazil'},
    {'name': 'Jason Momoa', 'follower_count': 115, 'description': 'Actor and Aquaman star', 'country': 'United States'},
    {'name': 'Bad Bunny', 'follower_count': 150, 'description': 'Reggaeton superstar', 'country': 'Puerto Rico'},
    {'name': 'Anne Hathaway', 'follower_count': 110, 'description': 'Actress', 'country': 'United States'},
    {'name': 'J Balvin', 'follower_count': 135, 'description': 'Latin music icon', 'country': 'Colombia'},
    {'name': 'Kylie Jenner', 'follower_count': 270, 'description': 'Reality star and businesswoman', 'country': 'United States'},
    {'name': 'Hugh Jackman', 'follower_count': 115, 'description': 'Actor and Wolverine star', 'country': 'Australia'},
    {'name': 'Post Malone', 'follower_count': 140, 'description': 'Rapper and singer', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 250, 'description': 'Model and reality star', 'country': 'United States'},
    {'name': 'Tom Holland', 'follower_count': 130, 'description': 'Actor and Spider-Man star', 'country': 'United Kingdom'},
    {'name': 'Megan Thee Stallion', 'follower_count': 135, 'description': 'Rapper', 'country': 'United States'},
    {'name': 'Lewis Hamilton', 'follower_count': 145, 'description': 'Formula 1 champion', 'country': 'United Kingdom'},
    {'name': 'Salma Hayek', 'follower_count': 110, 'description': 'Actress and producer', 'country': 'Mexico'},
    {'name': 'Pharrell Williams', 'follower_count': 120, 'description': 'Musician and producer', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 200, 'description': 'Reality star and entrepreneur', 'country': 'United States'},
    {'name': 'Chris Evans', 'follower_count': 115, 'description': 'Actor and Captain America star', 'country': 'United States'},
    {'name': 'Sofia Vergara', 'follower_count': 125, 'description': 'Actress and TV star', 'country': 'Colombia'},
    {'name': 'Timothée Chalamet', 'follower_count': 130, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Ricky Martin', 'follower_count': 120, 'description': 'Musician and actor', 'country': 'Puerto Rico'},
    {'name': 'Hailey Bieber', 'follower_count': 140, 'description': 'Model', 'country': 'United States'},
    {'name': 'Roger Federer', 'follower_count': 150, 'description': 'Tennis legend', 'country': 'Switzerland'},
    {'name': 'Alicia Keys', 'follower_count': 125, 'description': 'Musician and songwriter', 'country': 'United States'},
    {'name': 'Zac Efron', 'follower_count': 115, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Anitta', 'follower_count': 130, 'description': 'Brazilian music star', 'country': 'Brazil'},
    {'name': 'Kourtney Kardashian', 'follower_count': 190, 'description': 'Reality star and businesswoman', 'country': 'United States'},
    {'name': 'Mark Wahlberg', 'follower_count': 110, 'description': 'Actor and producer', 'country': 'United States'},
    {'name': 'Lizzo', 'follower_count': 135, 'description': 'Musician and body positivity icon', 'country': 'United States'},
    {'name': 'Rafael Nadal', 'follower_count': 145, 'description': 'Tennis superstar', 'country': 'Spain'},
    {'name': 'Jessica Alba', 'follower_count': 120, 'description': 'Actress and entrepreneur', 'country': 'United States'},
    {'name': 'Travis Scott', 'follower_count': 140, 'description': 'Rapper and producer', 'country': 'United States'},
    {'name': 'Deepika Padukone', 'follower_count': 150, 'description': 'Bollywood actress', 'country': 'India'},
    {'name': 'Matthew McConaughey', 'follower_count': 115, 'description': 'Actor', 'country': 'United States'},
    {'name': 'A$AP Rocky', 'follower_count': 130, 'description': 'Rapper and fashion icon', 'country': 'United States'},
    {'name': 'Novak Djokovic', 'follower_count': 145, 'description': 'Tennis champion', 'country': 'Serbia'},
    {'name': 'Penélope Cruz', 'follower_count': 110, 'description': 'Actress', 'country': 'Spain'},
    {'name': 'John Legend', 'follower_count': 125, 'description': 'Musician and TV personality', 'country': 'United States'},
    {'name': 'Bella Hadid', 'follower_count': 140, 'description': 'Supermodel', 'country': 'United States'},
    {'name': 'Conor McGregor', 'follower_count': 150, 'description': 'MMA fighter', 'country': 'Ireland'},
    {'name': 'Demi Lovato', 'follower_count': 135, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Idris Elba', 'follower_count': 115, 'description': 'Actor and DJ', 'country': 'United Kingdom'},
    {'name': 'Rosé', 'follower_count': 130, 'description': 'K-pop star (BLACKPINK)', 'country': 'South Korea'},
    {'name': 'Stephen Curry', 'follower_count': 145, 'description': 'Basketball superstar', 'country': 'United States'},
    {'name': 'Kate Winslet', 'follower_count': 110, 'description': 'Actress', 'country': 'United Kingdom'},
    {'name': 'Jimin', 'follower_count': 140, 'description': 'K-pop star (BTS)', 'country': 'South Korea'},
    {'name': 'Giannis Antetokounmpo', 'follower_count': 135, 'description': 'Basketball star', 'country': 'Greece'},
    {'name': 'Nicole Kidman', 'follower_count': 115, 'description': 'Actress', 'country': 'Australia'},
    {'name': 'Jungkook', 'follower_count': 150, 'description': 'K-pop star (BTS)', 'country': 'South Korea'},
    {'name': 'Céline Dion', 'follower_count': 125, 'description': 'Legendary singer', 'country': 'Canada'},
    {'name': 'Ryan Gosling', 'follower_count': 110, 'description': 'Actor', 'country': 'Canada'},
    {'name': 'Lisa', 'follower_count': 140, 'description': 'K-pop star (BLACKPINK)', 'country': 'Thailand'},
    {'name': 'Kevin Durant', 'follower_count': 135, 'description': 'Basketball star', 'country': 'United States'},
    {'name': 'Sandra Bullock', 'follower_count': 115, 'description': 'Actress', 'country': 'United States'},
    {'name': 'RM', 'follower_count': 145, 'description': 'K-pop star (BTS)', 'country': 'South Korea'},
    {'name': 'Aishwarya Rai', 'follower_count': 130, 'description': 'Bollywood actress', 'country': 'India'},
    {'name': 'Christian Bale', 'follower_count': 110, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Jennie', 'follower_count': 140, 'description': 'K-pop star (BLACKPINK)', 'country': 'South Korea'},
    {'name': 'Simone Biles', 'follower_count': 135, 'description': 'Gymnastics legend', 'country': 'United States'},
    {'name': 'Jude Law', 'follower_count': 115, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'V', 'follower_count': 150, 'description': 'K-pop star (BTS)', 'country': 'South Korea'},
    {'name': 'Naomi Osaka', 'follower_count': 130, 'description': 'Tennis star', 'country': 'Japan'},
    {'name': 'Hugh Grant', 'follower_count': 110, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Suga', 'follower_count': 145, 'description': 'K-pop star (BTS)', 'country': 'South Korea'},
    {'name': 'Anya Taylor-Joy', 'follower_count': 125, 'description': 'Actress', 'country': 'United States'},
    {'name': 'Daniel Craig', 'follower_count': 115, 'description': 'Actor and James Bond star', 'country': 'United Kingdom'},
    {'name': 'J-Hope', 'follower_count': 140, 'description': 'K-pop star (BTS)', 'country': 'South Korea'},
    {'name': 'Coco Gauff', 'follower_count': 130, 'description': 'Tennis prodigy', 'country': 'United States'},
    {'name': 'Tom Hardy', 'follower_count': 115, 'description': 'Actor', 'country': 'United Kingdom'},
    {'name': 'Jin', 'follower_count': 145, 'description': 'K-pop star (BTS)', 'country': 'South Korea'},
    {'name': 'Florence Pugh', 'follower_count': 125, 'description': 'Actress', 'country': 'United Kingdom'},
    {'name': 'Jake Gyllenhaal', 'follower_count': 110, 'description': 'Actor', 'country': 'United States'},
    {'name': 'IU', 'follower_count': 135, 'description': 'K-pop and acting star', 'country': 'South Korea'},
    {'name': 'Erling Haaland', 'follower_count': 140, 'description': 'Football rising star', 'country': 'Norway'},
    {'name': 'Keira Knightley', 'follower_count': 115, 'description': 'Actress', 'country': 'United Kingdom'},
    {'name': 'G-DRAGON', 'follower_count': 130, 'description': 'K-pop icon', 'country': 'South Korea'},
    {'name': 'Manny Pacquiao', 'follower_count': 135, 'description': 'Boxing legend', 'country': 'Philippines'},
    {'name': 'Amy Adams', 'follower_count': 110, 'description': 'Actress', 'country': 'United States'},
    {'name': 'BLACKPINK', 'follower_count': 150, 'description': 'K-pop supergroup', 'country': 'South Korea'},
    {'name': 'BTS', 'follower_count': 200, 'description': 'K-pop global phenomenon', 'country': 'South Korea'}
]
